name: Stable Docs Publish
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    if: github.repository_owner == 'Qiskit-Community'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U virtualenv setuptools wheel tox
          sudo apt-get install graphviz pandoc
      - name: Build docs stable
        env:
          QISKIT_DOCS_BUILD_TUTORIALS: 'always'
        run: tox -e docs
      - name: Bypass Jekyll Processing # Necessary for setting the correct css path
        run: touch docs/_build/html/.nojekyll
      - name: Set current version
        run: |
          echo "version=$(git describe --abbrev=0 | cut -d'.' -f1,2)" >> "$GITHUB_ENV"
      - name: Deploy stable
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/html
          target-folder: stable/${{ env.version }}